local_costmap:
  global_frame: odom        # Odometry 기준
  robot_base_frame: base_link
  update_frequency: 2.0     # 더 자주 업데이트하여 실시간 장애물 회피
  publish_frequency: 1.0
  static_map: false         # 정적 지도를 사용하지 않음
  rolling_window: true      # 로봇을 따라 지도가 움직임
  width: 2.0                # 로봇 주변 3x3미터 영역을 감시
  height: 2.0
  resolution: 0.05
  transform_tolerance: 1.0
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
